version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/myapp
    overwrite: true

hooks:
  BeforeInstall:
    - location: scripts/clean.sh
      timeout: 180
      runas: ubuntu

  AfterInstall:
    - location: scripts/start.sh
      timeout: 300
      runas: ubuntu
