version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      # Run your build script here, or remove if not needed
      - npm run build || echo "No build script defined, skipping"

artifacts:
  files:
    - '**/*'
